[package]
name = "piwasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = "*"
cosmwasm-std = "*"
serde = { version = "*", features = ["derive"] }
postcard = { version = "*", default-features = false, features = ["alloc"] }
